Repository Ebyrdeu/movie_jakarta, pull requests merged in 2024-03, with the labels that each got.

#24 Add MovieRepository with basic crud options #20
  pom.xml
  src/main/java/dev/ebyrdeu/movie_jakarta/repository/MovieRepository.java
  src/test/java/dev/ebyrdeu/movie_jakarta/repository/MovieRepositoryTest.java
Labels: enhancement

#33 21 update resource class
  pom.xml
  src/main/java/dev/ebyrdeu/movie_jakarta/dto/MovieDto.java
  src/main/java/dev/ebyrdeu/movie_jakarta/repository/MovieRepository.java
  src/main/java/dev/ebyrdeu/movie_jakarta/resource/HelloResource.java
  src/main/java/dev/ebyrdeu/movie_jakarta/resource/MovieResource.java
  src/main/resources/META-INF/persistence.xml
  src/main/resources/api/movie.http
  src/test/java/dev/ebyrdeu/movie_jakarta/dto/MovieDtoTest.java
  src/test/java/dev/ebyrdeu/movie_jakarta/repository/MovieRepositoryTest.java
  src/test/java/dev/ebyrdeu/movie_jakarta/resource/MovieResourceTest.java
Labels: enhancement

#37 drafter-package
  .github/release-drafter.config.yml
  .github/workflows/release-drafter.yml
Labels: devops

#38 Delete moviedb
  src/main/resources/movie_db/moviedb.sql
Labels: invalid, minor
